USERNAME = "" #Digite o nome de usuário
PASSWORD = "" #Digite a senha
PERCENT_OF_ALL_CASH_TO_HAND = 10 #Percentual de dinheiro que fica na mão
PREFERED_SOLO_ROBBERY = '18' #Código do roubo solo conforme planilha disponibilizada
PREFERED_GANG_ROBERRY = '2' #Código do roubo em gangue
TICKETS_STOP = 25 #Quantidade mínima de tickets antes de entrar em modo de espera
TICKETS_TO_RECOVER = 72 #Quantidade de tickets para reiniciar o bot
PERCENTAGE_OF_ADICIONAL_WAITING = 15 #Porcentagem extra de esperar durante os timers de pausa
MAX_ADDICTION = 90 #Vício máximo permitido
USE_VIRTUAL_GANG = False #True:Procura sempre uma gangue virutal para fazer parte, False:Não procura gangue virtual e participa de roubos apenas se disponível
PEOPLE_ON_NIGHTCLUB = 0 # 0:Run_Away, 1:Attack_everyone, 2:Attack_Only_Lower_Respect
PLAY_SONGS = True #Toca os sons de aviso
